project:
  type: website
  pre-render:
    - pre-render.R      

website:
  title: "quarto-with-desc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



